2018-08-09 13:07:39,719 - root - DEBUG - p12 location ---> /Users/reed.feldman/Desktop/symphonyPythonClient/resources/certificates/bot.user11.p12
2018-08-09 13:07:39,728 - root - DEBUG - Auth/authenticate()
2018-08-09 13:07:39,728 - root - DEBUG - Auth/authenticate() --> needed to authenticate
2018-08-09 13:07:39,728 - root - DEBUG - Auth/get_session_token()
